package LibraryProject;

import javax.swing.JOptionPane;


public class Login_As extends javax.swing.JFrame {

    public Login_As() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        checkbox1 = new java.awt.Checkbox();
        checkbox2 = new java.awt.Checkbox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login As");

        jPanel1.setLayout(null);

        label1.setBackground(new java.awt.Color(0, 153, 204));
        label1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label1.setText(" User Name");
        jPanel1.add(label1);
        label1.setBounds(98, 60, 84, 30);

        label2.setBackground(new java.awt.Color(51, 102, 255));
        label2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label2.setText(" Password");
        jPanel1.add(label2);
        label2.setBounds(100, 110, 80, 30);

        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(jTextField1);
        jTextField1.setBounds(200, 60, 180, 30);

        jPasswordField1.setBackground(new java.awt.Color(204, 204, 204));
        jPasswordField1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(200, 110, 180, 30);

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(200, 280, 90, 30);

        checkbox1.setBackground(new java.awt.Color(255, 255, 0));
        checkbox1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        checkbox1.setLabel("ADMIN");
        checkbox1.setName(""); // NOI18N
        jPanel1.add(checkbox1);
        checkbox1.setBounds(84, 210, 80, 30);

        checkbox2.setBackground(new java.awt.Color(255, 255, 0));
        checkbox2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        checkbox2.setLabel("USER");
        jPanel1.add(checkbox2);
        checkbox2.setBounds(330, 210, 70, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\USAMA\\Pictures\\Library Management.jpg")); // NOI18N
        jLabel1.setText("ADMIN");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -60, 569, 450);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String user = jTextField1.getText();
        String password = jPasswordField1.getText();
        if(user.length() == 0 || password.length() == 0)
            JOptionPane.showMessageDialog(null, "Enter All Information");
        else{
            if(checkbox1.getState() && checkbox2.getState()){
                JOptionPane.showMessageDialog(this, "Invalid Selection");
            }
            else if(checkbox1.getState()){
                LoginInterface obj = new LoginDAL();
                int found = obj.checkAdmin(user, password);
                if(found > 0){
                    AdminFunctions Admin = new AdminFunctions();
                    Admin.setVisible(true);
                }
                else
                    JOptionPane.showMessageDialog(null, "Admin not exist");
            }
            else if(checkbox2.getState()){
                LoginInterface obj = new LoginDAL();;
                int found = obj.checkUser(user, password);
                if(found > 0){
                    UserFunctions User = new UserFunctions();
                    User.setVisible(true);
                }
                else
                    JOptionPane.showMessageDialog(null, "User not exist");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_As.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_As.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_As.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_As.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_As().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Checkbox checkbox1;
    private java.awt.Checkbox checkbox2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    // End of variables declaration//GEN-END:variables
}
